Refacto contact page back+bit of front
WildCodeSchool/Blog-e-Boulga_Symfony pull request #11
Opened 2024-02-21 10:05 UTC by LuckyShuii

2024-02-21 15:05 UTC, Monost0ne requested changes

2024-02-21 15:05 UTC, Monost0ne commented on assets/styles/app.scss
> +@keyframes shake {
remove here

2024-02-22 08:27 UTC, Monost0ne approved these changes
gow

2024-02-22 08:38 UTC, Benja-san approved these changes

2024-02-22 08:38 UTC, Benja-san commented on templates/contact/index.html.twig
> +            {{ form_start(form, {'attr': { 'class': 'contactUsForm', 'novalidate': 'novalidate' }}) }}
remove novalidate, only for testing purpose

2024-02-22 08:38 UTC, Benja-san commented on templates/contact/index.html.twig
> +            {{ form_start(form, {'attr': { 'class': 'contactUsForm', 'novalidate': 'novalidate' }}) }}
unless you want your javascript to replace navigator error display ?

2024-02-22 08:38 UTC, Benja-san commented on src/Controller/ContactController.php
> +            'page' => 'contact',
is this variable usefull ?

2024-02-22 08:40 UTC, LuckyShuii commented on src/Controller/ContactController.php
> +            'page' => 'contact',
yes 🙏🏻

2024-02-22 08:46 UTC, merged