added page for header underline
WildCodeSchool/Blog-e-Boulga_Symfony pull request #12
Opened 2024-02-21 10:19 UTC by LuckyShuii

2024-02-21 15:14 UTC, Monost0ne approved these changes
go

2024-02-22 08:30 UTC, Benja-san requested changes

2024-02-22 08:30 UTC, Benja-san commented on src/Controller/AuthorController.php
> +            'page' => 'about'
à propos rather than about for french website

2024-02-22 08:48 UTC, Benja-san approved these changes

2024-02-22 08:48 UTC, merged