Crud admin article
WildCodeSchool/Blog-e-Boulga_Symfony pull request #16
Opened 2024-02-21 14:39 UTC by Monost0ne

scss not good actually, just first iteration

2024-02-21 14:54 UTC, LuckyShuii requested changes

2024-02-21 14:54 UTC, LuckyShuii commented on assets/styles/admin_article.scss
> +    font-family: 'Titillium Web', sans-serif;
isn't the font supposed to be globally applied throughout the project?

2024-02-21 14:54 UTC, LuckyShuii commented on src/Controller/AdminArticleController.php
> +            $entityManager->flush();
you forgot to set a creation date here

2024-02-21 14:54 UTC, LuckyShuii commented on src/Form/ArticleType.php
> +                    ]),
anglicisme "homepage" => translate to french

2024-02-21 14:54 UTC, LuckyShuii commented on src/Form/ArticleType.php
> +
remove blank space here

2024-02-21 14:54 UTC, LuckyShuii commented on templates/admin_article/_form.html.twig
> +    </div>
weird indentation

2024-02-21 14:54 UTC, LuckyShuii commented on templates/admin_article/_form.html.twig
> +</div><div>
<div> x2, put the second next line

2024-02-21 14:54 UTC, LuckyShuii commented on templates/admin_article/_form.html.twig
> +{{ form_end(form) }}
translate "save" to French  + are you really using the class "btn" that Symfony provided you?

2024-02-21 14:54 UTC, LuckyShuii commented on templates/admin_article/new.html.twig
> +{% block stylesheets %}{{ encore_entry_link_tags('admin_article') }}{% endblock %}
Translate title into French

2024-02-22 09:28 UTC, Benja-san approved these changes

2024-02-22 09:29 UTC, LuckyShuii approved these changes

2024-02-22 09:33 UTC, merged