end upload with flash
WildCodeSchool/Blog-e-Boulga_Symfony pull request #21
Opened 2024-02-22 16:21 UTC by Monost0ne

2024-02-22 16:47 UTC, LuckyShuii requested changes

2024-02-22 16:47 UTC, LuckyShuii commented on templates/admin/article/edit.html.twig
> +{#    {{ include('admin/article/_delete_form.html.twig') }}#}
dead code

2024-02-23 09:02 UTC, Benja-san approved these changes
Remove dead code (Lucas comment) and good to go

2024-02-23 09:21 UTC, LuckyShuii approved these changes

2024-02-23 09:21 UTC, merged